### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'messageChannel')

### ISSUE THREAD

**Issue by indrodev** [poolifier/poolifier#1496]
### Duplicate issue

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

TypeError: Cannot read properties of undefined (reading 'messageChannel')
    at exports.DynamicThreadPool.sendToWorker (/usr/src/app/node_modules/poolifier/lib/index.js:1:44151)
    at exports.DynamicThreadPool.executeTask (/usr/src/app/node_modules/poolifier/lib/index.js:1:42339)
    at /usr/src/app/node_modules/poolifier/lib/index.js:1:33310
    at new Promise (<anonymous>)
    at exports.DynamicThreadPool.execute (/usr/src/app/node_modules/poolifier/lib/index.js:1:32582)
    at HttpModeTask.process (/usr/src/app/dist/lib/Task/task.service.js:475:18)
    at HttpModeTask.execute (/usr/src/app/dist/lib/Task/task.service.js:289:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.processJob [as fn] (/usr/src/app/dist/utils/agenda/jobs/task.js:24:24) 

### Expected behavior

no error

### Actual behavior

throws error

### Steps to reproduce

when using DynamicThreadPool for a long time (got after 26hrs)

### poolifier version

^3.0.1

### Node.js version

v18.18.0

### System

  System:
    OS: Linux 5.15 Zorin OS 16.3
    CPU: (6) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 21.76 GB / 29.20 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh

**Comment by jerome-benoit** [comment]
Should be fixed in https://github.com/poolifier/poolifier/releases/tag/v3.0.2

**Comment by jimOnAir** [comment]
Still has this error on 3.1.20
```
TypeError: Cannot read properties of undefined (reading 'messageChannel')
    at exports.DynamicThreadPool.sendToWorker (/Users/dmitry/Code/platform/node_modules/poolifier/src/pools/thread/fixed.ts:55:37)
    at exports.DynamicThreadPool.executeTask (/Users/dmitry/Code/platform/node_modules/poolifier/src/pools/abstract-pool.ts:1915:10)
    at /Users/dmitry/Code/platform/node_modules/poolifier/src/pools/abstract-pool.ts:944:14
    at new Promise (<anonymous>)
    at exports.DynamicThreadPool.exe…r.service.ts:30:30)
```

**Comment by jerome-benoit** [comment]
Do you have way to reliability reproduce it?

**Comment by jerome-benoit** [comment]
> Still has this error on 3.1.20
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'messageChannel')
>     at exports.DynamicThreadPool.sendToWorker (/Users/dmitry/Code/platform/node_modules/poolifier/src/pools/thread/fixed.ts:55:37)
>     at exports.DynamicThreadPool.executeTask (/Users/dmitry/Code/platform/node_modules/poolifier/src/pools/abstract-pool.ts:1915:10)
>     at /Users/dmitry/Code/platform/node_modules/poolifier/src/pools/abstract-pool.ts:944:14
>     at new Promise (<anonymous>)
>     at exports.DynamicThreadPool.exe…r.service.ts:30:30)
> ```

Do you have a way to reliability reproduce it?

**Comment by jimOnAir** [comment]
No, I don't. Here is pool info just before error:
```
2024-02-27T05:45:12.439Z <debug>                [PlatformWorkerService] Pool worker nodes: [{"_events":{},"_eventsCount":0,"worker":{"_events":{"error":[null,null],"exit":[null,null]},"_eventsCount":6,"performance":{}},"info":{"id":3,"type":"thread","dynamic":false,"ready":true,"stealing":false,"taskFunctionNames":["default","fn1"]},"usage":{"tasks":{"executed":195,"executing":0,"queued":0,"maxQueued":0,"sequentiallyStolen":0,"stolen":0,"failed":0},"runTime":{"history":[]},"waitTime":{"history":[]},"elu":{"idle":{"history":[]},"active":{"history":[]}}},"messageChannel":{"port1":{},"port2":{}},"tasksQueueBackPressureSize":100,"tasksQueue":{"size":0,"maxSize":0},"onBackPressureStarted":false,"taskFunctionsUsage":{}}]
2024-02-27T05:45:12.439Z <debug>                [PlatformWorkerService] Pool worker info: {"version":"3.1.20","type":"dynamic","worker":"thread","started":true,"ready":true,"strategy":"ROUND_ROBIN","strategyRetries":0,"minSize":1,"maxSize":10,"workerNodes":1,"idleWorkerNodes":1,"busyWorkerNodes":0,"executedTasks":195,"executingTasks":0,"failedTasks":0}
2024-02-27T05:45:12.440Z <error>                [PlatformWorkerService] TypeError: Cannot read properties of undefined (reading 'messageChannel') 
```
